### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by paolodina** [tralves/nativescript-vue-webpack-template#16]
Hello and thanks for the effort put on this template and NativeScript/Vue integration.

I'm following the steps in order to test the template. Everything seems fine (`webpack --watch --env.tns --env.android` and `tns debug android` output is fine) until the app is deployed on the emulator, where I get an exception. Any help greatly appreciated.

```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Cannot compile /data/data/org.nativescript.hellonsvue/files/app/app.js

SyntaxError: Unexpected token import
File: "file:///data/data/org.nativescript.hellonsvue/files/app/app.js, line: 4, column: 0

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266


SyntaxError: Unexpected token import
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266


	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5406)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: com.tns.NativeScriptException: 

Cannot compile /data/data/org.nativescript.hellonsvue/files/app/app.js

SyntaxError: Unexpected token import
File: "file:///data/data/org.nativescript.hellonsvue/files/app/app.js, line: 4, column: 0

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266


SyntaxError: Unexpected token import
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266


	at com.tns.Runtime.runModule(Native Method)
	at com.tns.Runtime.runModule(Runtime.java:530)
	at com.tns.Runtime.run(Runtime.java:522)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
	... 8 more

```

**Comment by tralves** [comment]
I am not on my computer now, but meanwhile please make sure you are running
tns debug from the tns folder.

I will look into it later. Thanks!

**Comment by paolodina** [comment]
Of course I'm so silly, it works now.
