### ISSUE TITLE
Creation from Template fails on Windows 10

### ISSUE THREAD

**Issue by rwuttke** [tralves/nativescript-vue-webpack-template#21]
Using the example give for creating a new app:

**tns create sample-app --template https://github.com/tralves/nativescript-vue-webpack-template**

Fails with the following error:

```
Installing  https://github.com/tralves/nativescript-vue-webpack-template
listing files
app
linking  D:\projects\nativescript\version\sample-app\package.json D:\projects\nativescript\version\sample-app\tns\package.json
linking  D:\projects\nativescript\version\sample-app\package-lock.json D:\projects\nativescript\version\sample-app\tns\package-lock.json
linking  D:\projects\nativescript\version\sample-app\node-modules D:\projects\nativescript\version\sample-app\tns\node-modules
fs.js:1021
  return binding.symlink(preprocessSymlinkDestination(target, type, path),
                 ^

Error: EPERM: operation not permitted, symlink 'D:\projects\nativescript\version\sample-app\node-modules' -> 'D:\projects\nativescript\version\sample-app\tns\node-modules'
    at Object.fs.symlinkSync (fs.js:1021:18)
    at symlinkFromTns (D:\projects\nativescript\version\sample-app\node_modules\nativescript-vue-webpack\postinstall.js:40:6)
    at Object.<anonymous> (D:\projects\nativescript\version\sample-app\node_modules\nativescript-vue-webpack\postinstall.js:15:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
Command npm.cmd install https://github.com/tralves/nativescript-vue-webpack-template --silent --save-exact --save failed with exit code 1

```
Versions:

**vue-cli@2.9.2
nativescript@3.3.1
npm@5.6.0
node@8.5.0**

**Microsoft Windows [Version 10.0.16299.64]**

Running it with a terminal started as Administrator

```
Installing  https://github.com/tralves/nativescript-vue-webpack-template
listing files
app
linking  D:\projects\nativescript\version\sample-app\package.json D:\projects\nativescript\version\sample-app\tns\package.json
linking  D:\projects\nativescript\version\sample-app\package-lock.json D:\projects\nativescript\version\sample-app\tns\package-lock.json
linking  D:\projects\nativescript\version\sample-app\node-modules D:\projects\nativescript\version\sample-app\tns\node-modules
linking  D:\projects\nativescript\version\sample-app\app\App_Resources D:\projects\nativescript\version\sample-app\tns\app\App_Resources
linking  D:\projects\nativescript\version\sample-app\app\images D:\projects\nativescript\version\sample-app\tns\app\images
+ nativescript-vue-webpack@0.1.0
added 116 packages in 20.46s
+ tns-template-hello-world@3.3.0
added 1 package and removed 113 packages in 5.475s
Command failed: npm uninstall tns-template-hello-world --save
fs.js:1021
  return binding.symlink(preprocessSymlinkDestination(target, type, path),
                 ^

Error: EEXIST: file already exists, symlink 'D:\projects\nativescript\version\sample-app\node-modules' -> 'D:\projects\nativescript\version\sample-app\tns\node-modules'
    at Object.fs.symlinkSync (fs.js:1021:18)
    at symlinkFromTns (D:\projects\nativescript\version\sample-app\node_modules\nativescript-vue-webpack\postinstall.js:40:6)
    at Object.<anonymous> (D:\projects\nativescript\version\sample-app\node_modules\nativescript-vue-webpack\postinstall.js:15:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nativescript-vue-webpack@0.1.0 postinstall: `node postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nativescript-vue-webpack@0.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Robert Wuttke\AppData\Roaming\npm-cache\_logs\2017-12-03T09_27_33_699Z-debug.log
```

I have attached the debug log.
[2017-12-03T09_27_33_699Z-debug.log](https://github.com/tralves/nativescript-vue-webpack-template/files/1524624/2017-12-03T09_27_33_699Z-debug.log)

**Comment by rwuttke** [comment]
Running it with a terminal started as Administrator

```
Installing  https://github.com/tralves/nativescript-vue-webpack-template
listing files
app
linking  D:\projects\nativescript\versio
[2017-12-03T09_27_33_699Z-debug.log](https://github.com/tralves/nativescript-vue-webpack-template/files/1524621/2017-12-03T09_27_33_699Z-debug.log)
n\sample-app\package.json D:\projects\nativescript\version\sample-app\tns\package.json
linking  D:\projects\nativescript\version\sample-app\package-lock.json D:\projects\nativescript\version\sample-app\tns\package-lock.json
linking  D:\projects\nativescript\version\sample-app\node-modules D:\projects\nativescript\version\sample-app\tns\node-modules
linking  D:\projects\nativescript\version\sample-app\app\App_Resources D:\projects\nativescript\version\sample-app\tns\app\App_Resources
linking  D:\projects\nativescript\version\sample-app\app\images D:\projects\nativescript\version\sample-app\tns\app\images
+ nativescript-vue-webpack@0.1.0
added 116 packages in 20.46s
+ tns-template-hello-world@3.3.0
added 1 package and removed 113 packages in 5.475s
Command failed: npm uninstall tns-template-hello-world --save
fs.js:1021
  return binding.symlink(preprocessSymlinkDestination(target, type, path),
                 ^

Error: EEXIST: file already exists, symlink 'D:\projects\nativescript\version\sample-app\node-modules' -> 'D:\projects\nativescript\version\sample-app\tns\node-modules'
    at Object.fs.symlinkSync (fs.js:1021:18)
    at symlinkFromTns (D:\projects\nativescript\version\sample-app\node_modules\nativescript-vue-webpack\postinstall.js:40:6)
    at Object.<anonymous> (D:\projects\nativescript\version\sample-app\node_modules\nativescript-vue-webpack\postinstall.js:15:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nativescript-vue-webpack@0.1.0 postinstall: `node postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nativescript-vue-webpack@0.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Robert Wuttke\AppData\Roaming\npm-cache\_logs\2017-12-03T09_27_33_699Z-debug.log
```

I have attached the debug log.

**Comment by rwuttke** [comment]
Sorry, clicked the Close and comment button. Mea culpa.

**Comment by tralves** [comment]
Hum... This template is using symlinks for several files and folders, and that doesn't seem to work on windows. An easy workaround would be using [symlink-or-copy](https://www.npmjs.com/package/symlink-or-copy).

**Comment by tralves** [comment]
Man! This was much harder that it seemed!

After spending way too much time on this, I decided to revert most of what I have done... I may have fixed your bug.

Can you please retry, again with Administrator privileges?
Thanks

**Comment by rwuttke** [comment]
Sorry I took so long to get back to you.

That works now with Administrator privileges.

Without Admin privileges gives:

```
Installing  https://github.com/tralves/nativescript-vue-webpack-template                                                                 
listing files                                                                                                                            
fs.js:904                                                                                                                                
  return binding.readdir(pathModule._makeLong(path), options.encoding);                                                                  
                 ^                                                                                                                       
                                                                                                                                         
Error: ENOENT: no such file or directory, scandir 'D:\projects\nativescript\sample-app\tns'                                              
    at Object.fs.readdirSync (fs.js:904:18)                                                                                              
    at Object.<anonymous> (D:\projects\nativescript\sample-app\node_modules\nativescript-vue-webpack\postinstall.js:9:4)                 
    at Module._compile (module.js:635:30)                                                                                                
    at Object.Module._extensions..js (module.js:646:10)                                                                                  
    at Module.load (module.js:554:32)                                                                                                    
    at tryModuleLoad (module.js:497:12)                                                                                                  
    at Function.Module._load (module.js:489:3)                                                                                           
    at Function.Module.runMain (module.js:676:10)                                                                                        
    at startup (bootstrap_node.js:187:16)                                                                                                
    at bootstrap_node.js:608:3                                                                                                           
Command npm.cmd install https://github.com/tralves/nativescript-vue-webpack-template --silent --save-exact --save failed with exit code 1
```

Thanks for the work so far.

**Comment by tralves** [comment]
Yup... windows need special permissions for symlinks to work.

In any case I may remove the symlinks, as some people have been reporting issues.

I'll leave this issue open until we decide what's best.

**Comment by waptaxi** [comment]
Any news on this issue? 
I also can't install on Windows 7.

**Comment by RedKage** [comment]
Same here, using admin cmd

```
Installing  https://github.com/tralves/nativescript-vue-webpack-template
listing files
fs.js:924
  return binding.readdir(pathModule.toNamespacedPath(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir 'C:\test2\hello-ns-vue\tns'
    at Object.fs.readdirSync (fs.js:924:18)
    at Object.<anonymous> (C:\test2\hello-ns-vue\node_modules\nativescript-vue-webpack\postinstall.js:9:4)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
Command npm.cmd install https://github.com/tralves/nativescript-vue-webpack-template --silent --save-exact --save failed with exit code 1
# create

```

**Comment by wa05** [comment]
Making it work using bash as Admin

**Comment by tralves** [comment]
This template is being deprecated in favor of the [Vue Cli template](https://github.com/nativescript-vue/vue-cli-template). `vue-cli` simply deals with these problems much nicely...
