### ISSUE TITLE
Unknown Token Import even though i am in the tns directory

### ISSUE THREAD

**Issue by maxemiliang** [tralves/nativescript-vue-webpack-template#28]
Hello i have read #16 and i can confirm that i am in tns directory but it still wont work, webpack compiles fine but the moment i try to run it on my test phone it just spits out this:
```
Searching for devices...
Skipping prepare.
Using  C:\Users\maxem\Documents\Projects\finest-client-app\platforms\android\app\build\outputs\apk\finestapp-debug.apk
device: 63877e12 debug port: 40000

ActivityManager: Start proc 28424:org.nativescript.finestapp/u0a315 for embryo org.nativescript.finestapp
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException:
System.err:
System.err: Cannot compile /data/data/org.nativescript.finestapp/files/app/app.js
System.err:
System.err: SyntaxError: Unexpected token import
System.err: File: "file:///data/data/org.nativescript.finestapp/files/app/app.js, line: 4, column: 0
System.err:
System.err: StackTrace:
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:
System.err:
System.err: SyntaxError: Unexpected token import
System.err: File: "<unknown>, line: 1, column: 265
System.err:
System.err: StackTrace:
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6037)
System.err:     at android.app.ActivityThread.-wrap1(Unknown Source:0)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
System.err:     at android.os.Looper.loop(Looper.java:164)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6809)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
System.err: Caused by: com.tns.NativeScriptException:
System.err:
System.err: Cannot compile /data/data/org.nativescript.finestapp/files/app/app.js
System.err:
System.err: SyntaxError: Unexpected token import
System.err: File: "file:///data/data/org.nativescript.finestapp/files/app/app.js, line: 4, column: 0
System.err:
System.err: StackTrace:
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:
System.err:
System.err: SyntaxError: Unexpected token import
System.err: File: "<unknown>, line: 1, column: 265
System.err:
System.err: StackTrace:
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:
System.err:     at com.tns.Runtime.runModule(Native Method)
System.err:     at com.tns.Runtime.runModule(Runtime.java:530)
System.err:     at com.tns.Runtime.run(Runtime.java:522)
System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1129)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6034)
System.err:     ... 8 more
ActivityManager: Process org.nativescript.finestapp (pid 28424) has died: fore TOP
# NativeScript Debugger did not start in time #
```

**Comment by maxemiliang** [comment]
Got it working after i removed everything and created the app again
