### ISSUE TITLE
Error running webpack --watch --env.tns --env.android

### ISSUE THREAD

**Issue by wa05** [tralves/nativescript-vue-webpack-template#30]
Node v9.50
Tns 3.4.2

Bash throws

F:\wamp64\www\hello-ns-vue\node_modules\webpack-cli\bin\webpack.js:237
                                throw err;
                                ^

Error: invalid "instanceof" keyword value Promise
    at getConstructor (F:\wamp64\www\hello-ns-vue\node_modules\ajv-keywords\keywords\instanceof.js:52:11)
    at Ajv.compile (F:\wamp64\www\hello-ns-vue\node_modules\ajv-keywords\keywords\instanceof.js:21:27)
    at Object.useCustomRule (F:\wamp64\www\hello-ns-vue\node_modules\webpack\node_modules\ajv\lib\compile\index.js:289:26)
    at Object.generate_custom [as code] (F:\wamp64\www\hello-ns-vue\node_modules\webpack\node_modules\ajv\lib\dotjs\custom.js:31:24)
    at Object.generate_validate [as validate] (F:\wamp64\www\hello-ns-vue\node_modules\webpack\node_modules\ajv\lib\dotjs\validate.js:228:37)
    at Object.generate_anyOf [as code] (F:\wamp64\www\hello-ns-vue\node_modules\webpack\node_modules\ajv\lib\dotjs\anyOf.js:34:27)
    at generate_validate (F:\wamp64\www\hello-ns-vue\node_modules\webpack\node_modules\ajv\lib\dotjs\validate.js:228:37)
    at localCompile (F:\wamp64\www\hello-ns-vue\node_modules\webpack\node_modules\ajv\lib\compile\index.js:99:22)
    at Ajv.compile (F:\wamp64\www\hello-ns-vue\node_modules\webpack\node_modules\ajv\lib\compile\index.js:67:13)
    at _compile (F:\wamp64\www\hello-ns-vue\node_modules\webpack\node_modules\ajv\lib\ajv.js:328:29)
    at Ajv.compile (F:\wamp64\www\hello-ns-vue\node_modules\webpack\node_modules\ajv\lib\ajv.js:114:34)
    at validateObject (F:\wamp64\www\hello-ns-vue\node_modules\webpack\lib\validateSchema.js:36:23)
    at validateSchema (F:\wamp64\www\hello-ns-vue\node_modules\webpack\lib\validateSchema.js:31:10)
    at processConfiguredOptions (F:\wamp64\www\hello-ns-vue\node_modules\webpack-cli\bin\convert-argv.js:156:48)
    at module.exports (F:\wamp64\www\hello-ns-vue\node_modules\webpack-cli\bin\convert-argv.js:150:10)
    at yargs.parse (F:\wamp64\www\hello-ns-vue\node_modules\webpack-cli\bin\webpack.js:234:39)
    at Object.parse (F:\wamp64\www\hello-ns-vue\node_modules\webpack-cli\node_modules\yargs\yargs.js:539:18)
    at F:\wamp64\www\hello-ns-vue\node_modules\webpack-cli\bin\webpack.js:212:8
    at Object.<anonymous> (F:\wamp64\www\hello-ns-vue\node_modules\webpack-cli\bin\webpack.js:504:3)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at C:\Users\walte\AppData\Roaming\npm\node_modules\webpack-cli\bin\webpack.js:15:3
    at Object.<anonymous> (C:\Users\walte\AppData\Roaming\npm\node_modules\webpack-cli\bin\webpack.js:504:3)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\walte\AppData\Roaming\npm\node_modules\webpack\bin\webpack.js:12:2)

**Comment by marcelvanheist** [comment]
worked for me when using `./node_modules/.bin/webpack --watch --env.tns --env.ios` instead of global webpack

**Comment by billgloff** [comment]
Or you can do:  `npx webpack --watch --env.tns --env.ios`

**Comment by tralves** [comment]
This template is being deprecated in favor of the [Vue Cli template](https://github.com/nativescript-vue/vue-cli-template). `vue-cli` simply deals with these problems much nicely...
