### ISSUE TITLE
Error creating the project

### ISSUE THREAD

**Issue by Steffo18** [tralves/nativescript-vue-webpack-template#31]
Hi, I'm creating a new NativeScript app with Vue and this template.
When  I try to do

`tns create sample-app --template https://github.com/tralves/nativescript-vue-webpack-template`

I get this error:

```
Error: EPERM: operation not permitted, symlink 'C:\workspace\Test\sample-app\package.json' -> 'C:\workspace\Test\sample-app\tns\package.json'
    at Object.fs.symlinkSync (fs.js:1014:18)
    at symlinkFromTns (C:\workspace\Test\sample-app\node_modules\nativescript-vue-webpack\postinstall.js:40:6)
    at Object.<anonymous> (C:\workspace\Test\sample-app\node_modules\nativescript-vue-webpack\postinstall.js:13:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
Command npm.cmd install https://github.com/tralves/nativescript-vue-webpack-template --silent --save-exact --save failed with exit code 1
```

How can I `solve?`

**Comment by tralves** [comment]
This template is being deprecated in favor of the [Vue Cli template](https://github.com/nativescript-vue/vue-cli-template). `vue-cli` simply deals with these problems much nicely...
